//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class AppConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppConfig defaultInstance = ((AppConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppConfig())));
        
        public static AppConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhYzc5N2M4MmNiMGI2MWMyOGQxYTZlMTViNzQ4ODUwYiIsIm5i" +
            "ZiI6MTcyNTUzMTQ0Mi40NDM3ODksInN1YiI6IjY2ZDk4NDkzMzM3NmE1MDNiNmI4ZDVkYiIsInNjb3Bl" +
            "cyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.SjJ8YL_CNhrC94D1sFAnjddhBUW5bspE0WvBSZry1" +
            "eY")]
        public string auth {
            get {
                return ((string)(this["auth"]));
            }
        }
    }
}
